var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "           x x                                                                  ",
   "          xxxxx                                   x x                           ",
   "           xxx                                   xxxxx                          ",
   "            x                  x x                xxx           xxx xxx         ",
   "                              xxxxx                x           xx!!x!!xx        ",
   "                               xxx                            xx!!!!!!!xx       ",
   "                    o o         x                              xx!!!!!xx        ",
   "  xx                                                            xx!!!xx         ",
   "  x                                                              xx!xx       o  ",
   "  x     @           xxx             o o                    o       v         o  ",
   "  x    xxx          x x                   o o                                   ",
   "  x    x x          x x  o         xxxxx                  xxx               xx  ",
   "  x    x x          x x            x   x xxxxx            x x                x  ",
   "  x    x x   xxxx   x x  o         x   x x   x            x xx               x  ",
   "  x    x x   x  x   x x            x   x x   x            x  x   xxxxx       x  ",
   "  xxxxxx xxxxx  xxxxx xxxxxxxxxx  xx   xxx   xxxxxxxxxx   x  xxxxx   xxxxxxxxx  ",
   "                               x  x                   x   x                     ",
   "                             xx!!!xx                 xx!!!xx                    ",
   "                            xx!!!!!xx               xx!!!!!xx                   ",
   "                            xxx!!!xxx               xxx!!!xxx                   ",
   "                             xxx!xxx                 xxx!xxx                    ",
   "                              xxxxx                   xxxxx                     ",
   "								 						 						",
   "								 						 					    "],
  ["                                                                                ",
   "          x x                                                                   ",
   "         x!!!x                                                                  ",
   "          x!x                                                                   ",
   "      o    v                                                                    ",
   "      o                        x x                              xxx xxx         ",
   "                              x!!!x                            xxxxxxxxx        ",
   "     xxx                       x!x                            xxxxxxxxxxx       ",
   "     x x                        v                   o          xxxxxxxxx        ",
   " @   x x                                                        xxxxxxx         ",
   "xxx  x x             o                             x x           xxxxx          ",
   "  x  x x             o                            x!!!x            x            ",
   "  x  x x      o                           o o      x!x                          ",
   "  x  x x      o     xxx  o                          v                     o     ",
   "  x  x x            x x                  xxxxx              o      o            ",
   "  x  x x     xxxx   x x  o           o   x   x                            o    o",
   "  x  x x     x  x   x x                  x   x            xxxx   xxxxx          ",
   "  xxxx xx  xxx  xxxxx xxxxxxxxxx  xxxxxxxx   xxxxxxxxxx   x  xxxxx   xxxxxxxxx  ",
   "        x  x                   x  x                   x   x                  x  ",
   "      xx!!!xx                xx!!!xx                 xx!!!xx                 x  ",
   "     xx!!!!!xx              xx!!!!!xx               xx!!!!!xx                xxx",
   "     xxx!!!xxx              xxx!!!xxx               xxx!!!xxx                   ",
   "      xxx!xxx                xxx!xxx                 xxx!xxx                    ",
   "       xxxxx                  xxxxx                   xxxxx                     ",
   "								 						 						",
   "								 						 					    "],
  ["                                                                                ",
   "                                                                                ",
   "       x x                                                                      ",
   "      x!!!x                                       x x                           ",
   "       x!x                                       xxxxx                          ",
   "        v                      x x                xxx           xxx xxx         ",
   "                              x!!!x                x           xx!!x!!xx        ",
   "     xxx xxx                   x!x                            xx!!!!!!!xx       ",
   "    xxxxxxxxx                   v                              xx!!!!!xx        ",
   "   xxxxxxxxxxx                                                  xx!!!xx         ",
   "    xxxxxxxxx                                                    xx!xx       o  ",
   "     xxxxxxx                                                       v         o  ",
   "      xxxxx                               o o               o                   ",
   "        x                                                                   xxxx",
   "                                         xxxxx            xxxxx          o  x   ",
   "         o               o               x x x            x x x         xxxxx   ",
   "                                          x x              x x          x       ",
   "xxxxxxxxxxxxxxxxxxxx o   o              xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx     xxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxx  x  xxxxxxx     xxxxxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx   o   xxxxx o     xxxx       xxxxxxxxx  x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxx     xxxxx         xx      xxxxxxxxxx   o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxx o xxxxx o              xxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                              xxxxxxxxxxxxxxx o xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "				                                                                ",
   "		@	                                                                    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;